# Generated by Django 5.0.5 on 2024-07-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroutine',
            name='days',
            field=models.CharField(default='M,T,W,Th,F,Sa,Su', max_length=50),
            preserve_default=False,
        ),
    ]
