# Generated by Django 5.0.5 on 2024-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_university_userroutine_useruniversity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroutine',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
