# Generated by Django 5.0.5 on 2024-06-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_userroutine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroutine',
            name='type',
        ),
    ]
