# Generated by Django 5.0.5 on 2024-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseweeklyreading',
            name='chapter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courseweeklytopic',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
